name: Humbug
main: com.untamedears.humbug.Humbug
version: 1.4.3
description: toggles various functionality
author: erocs
database: false
commands:
  humbug:
    description: Gets and sets Humbugs settings
    usage: /humbug <setting> [<value>]
    permission: humbug.console
  introbook:
    description: Creates the intro book for new players
    usage: /introbook [<playerName>]
    permission: humbug.admin.introbook
permissions:
  humbug.console:
    description: Console commands for Humbug
    default: false
  humbug.admin:
    description: Admin commands for Humbug
    default: op
    children:
      humbug.admin.introbook: true
